import Head from 'next/head'
import Image from 'next/image'
import { Inter } from 'next/font/google'
import styles from '../styles/Home.module.css'
import { useState } from 'react';
import RegisterForm from '../components/RegisterForm';
import LoginForm from '../components/LoginForm';
import Vault from '../components/Vault';


function Home() {

  const [step, setStep] = useState<'login' | 'register' | 'vault'>('login');
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by next app" />
        <link rel="icon" href="/favicone.ico" />
      </Head>

      <main>
        {step === "register" && <RegisterForm />}
        {step === "login" && <LoginForm />}
        {step === "vault" && <Vault />}
      </main>
    </div>
  )
}

export default Home;